mutation CreateUser($user: UserCreateInput!) {
  createOneUser(data: $user) {
    id
  }
}

query getUsers {
  users {
    id
    email
    name
    projects {
      name
      views {
        name
        translation {
          key
          label
          languages {
            value
            language {
              name
            }
          }
        }
      }
    }
  }
}

query getTranslationsByLanguages {
  languages(where: { projects: { every: { id: { equals: 1 } } } }) {
    name
    translations {
      value
      translation {
        key
        label
      }
    }
  }
}


# Query Variables
{
  "user": {
    "email": "amoutonbrady@gmail.com",
    "name": "Alexandre Mouton-Brady",
    "password": "alexandre"
  }
}