export const SECRET = process.env.SECRET || 'hello'
export const protectedPaths = [
  'Query.user',
  'Query.users',
  'Query.project',
  'Query.projects',
  'Query.language',
  'Query.languages',
  'Query.languagesOnTranslations',
  'Query.translation',
  'Query.translations',
  'Query.view',
  'Query.views',

  'Mutation.createOneUser',
  'Mutation.updateOneUser',
  'Mutation.deleteOneUser',
  'Mutation.createOneProject',
  'Mutation.updateOneProject',
  'Mutation.deleteOneProject',
  'Mutation.createOneView',
  'Mutation.updateOneView',
  'Mutation.deleteOneView',
  'Mutation.createOneTranslation',
  'Mutation.updateOneTranslation',
  'Mutation.deleteOneTranslation',
  'Mutation.createOneLanguage',
  'Mutation.updateOneLanguage',
  'Mutation.deleteOneLanguage',
  'Mutation.createOneLanguagesOnTranslations',
  'Mutation.updateOneLanguagesOnTranslations',
  'Mutation.deleteOneLanguagesOnTranslations',
]
